apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app
  labels:
    app: node-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-label
  template:
    metadata:
      namespace: node-app
      labels:
        app: node-label
    spec:
      containers:
        - name: node-app-container
          image: shravan112/node-app
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
